###
# @name get_repos_from_github
GET https://api.github.com/user/repos
Authorization: token {{$dotenv GITHUB_TOKEN}}

###
# @name get_file
GET {{baseUrl}}
Authorization: Bearer {{$dotenv BEARER_TOKEN}}

###
# @name health
GET {{baseUrl}}/health
